export const mockEmployees = [
  {
    id: "1",
    name: "Sarah Johnson",
    role: "Senior Hair Stylist",
    department: "Hair Styling",
    status: "Active",
  },
  {
    id: "2",
    name: "Emily Chen",
    role: "Nail Technician",
    department: "Nail Care",
    status: "Active",
  },
  {
    id: "3",
    name: "Michael Rodriguez",
    role: "Massage Therapist",
    department: "Massage",
    status: "Active",
  },
  {
    id: "4",
    name: "Jessica Williams",
    role: "Esthetician",
    department: "Skin Care",
    status: "Active",
  },
  {
    id: "5",
    name: "David Kim",
    role: "Receptionist",
    department: "Reception",
    status: "Active",
  },
  {
    id: "6",
    name: "Lisa Thompson",
    role: "Junior Stylist",
    department: "Hair Styling",
    status: "Active",
  },
]

export const mockTasks = [
  {
    id: "1",
    title: "Client Consultation - Mrs. Anderson",
    description: "Initial consultation for bridal hair styling package",
    assignedTo: "Sarah Johnson",
    priority: "High",
    status: "Pending",
    dueDate: "2024-01-15",
  },
  {
    id: "2",
    title: "Inventory Check - Nail Products",
    description: "Monthly inventory check for nail care products",
    assignedTo: "Emily Chen",
    priority: "Medium",
    status: "In Progress",
    dueDate: "2024-01-20",
  },
  {
    id: "3",
    title: "Equipment Maintenance",
    description: "Routine maintenance of massage equipment",
    assignedTo: "Michael Rodriguez",
    priority: "Medium",
    status: "Completed",
    dueDate: "2024-01-10",
  },
  {
    id: "4",
    title: "Staff Training - New Facial Techniques",
    description: "Training session on latest facial treatment techniques",
    assignedTo: "Jessica Williams",
    priority: "High",
    status: "Pending",
    dueDate: "2024-01-25",
  },
  {
    id: "5",
    title: "Customer Follow-up Calls",
    description: "Follow up with clients from last week",
    assignedTo: "David Kim",
    priority: "Low",
    status: "In Progress",
    dueDate: "2024-01-18",
  },
]
